/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../../index";

/**
 * @example
 *     {}
 */
export interface JobsListRequest {
    /**
     * The unique key identifying the corpus with the job.
     */
    corpusKey?: Vectara.CorpusKey | Vectara.CorpusKey[];
    /**
     * Get jobs after a date time.
     */
    after?: Date;
    /**
     * Indicates the states the jobs can be in.
     */
    state?: Vectara.JobState | Vectara.JobState[];
    /**
     * The maximum number of documents to return at one time.
     */
    limit?: number;
    /**
     * Used to the retrieve the next page of documents after the limit has been reached.
     */
    pageKey?: string;
}
