/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Vectara from "../../../../../api/index";
import * as core from "../../../../../core";
import { ApiRole } from "../../../../types/ApiRole";

export const UpdateAppClientRequest: core.serialization.Schema<
    serializers.UpdateAppClientRequest.Raw,
    Vectara.UpdateAppClientRequest
> = core.serialization.object({
    description: core.serialization.string().optional(),
    apiRoles: core.serialization.property("api_roles", core.serialization.list(ApiRole).optional()),
});

export declare namespace UpdateAppClientRequest {
    interface Raw {
        description?: string | null;
        api_roles?: ApiRole.Raw[] | null;
    }
}
