/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index.js";
import * as Vectara from "../index.js";
import * as core from "../../core/index.js";

export class TooManyRequestsError extends errors.VectaraError {
    constructor(body: Vectara.Error_, rawResponse?: core.RawResponse) {
        super({
            message: "TooManyRequestsError",
            statusCode: 429,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, TooManyRequestsError.prototype);
    }
}
