/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ApiKeysListRequest {
    /**
     * Max number of API keys to return at one time.
     */
    limit?: number;
    /**
     * Used to the retrieve the next page of API keys after the limit has been reached.
     */
    pageKey?: string;
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    requestTimeout?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    requestTimeoutMillis?: number;
}
