/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UpdateApiKeyRequest {
    /** Indicates whether to disable or enable an API key. */
    enabled?: boolean;
}
