/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../index";

/**
 * The parameters to search one corpus.
 */
export interface SearchCorpusParameters extends Vectara.SearchCorpus, Vectara.SearchParameters {}
