/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../../index.js";

/**
 * @example
 *     {
 *         generated_text: "generated_text",
 *         documents: [{
 *                 text: "text"
 *             }],
 *         model_name: "vhc-large-10"
 *     }
 */
export interface HallucinationCorrectionRequest {
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    "Request-Timeout"?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    "Request-Timeout-Millis"?: number;
    /** The generated text to be evaluated. The hallucination corrector reviews this text and applies corrections based on the provided source documents. */
    generated_text: string;
    /** The source documents that were used to generate the text. */
    documents: Vectara.HcmSourceDocument[];
    /** The name of the LLM model to use for hallucination correction. */
    model_name: string;
    /** Optional query that provides context for the expected response format and factual information. When provided, enables query-aware hallucination correction that considers the specific response format and factual context expected for the query. */
    query?: string;
}
