/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface AuthGetTokenRequest {
    clientId?: string;
    clientSecret?: string;
    grantType?: "client_credentials";
}
