/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../index.js";

export interface UsersCreateResponse extends Vectara.User {
    /** A one time code for the newly created user to create a password. This is optional, and is only populated for some Vectara deployments. */
    one_time_code?: string;
    /** The link where to enter the `one_time_code`. This is optional, and is only populated for some Vectara deployments. */
    one_time_code_link?: string;
}
