/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

/**
 * What actions a principal can take on the Vectara platform.
 */
export interface ApiPolicy {
    /** The name of the API role. */
    name: string;
    /**
     * Operations that are allowed by the API role. Each operation may only allow
     * certain resources that are described by a resource path to resource value
     * map. If the value is null, then the operation is allowed on any resource.
     */
    allowedOperations: Record<string, Vectara.ApiOperationPolicy>;
}
