/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Roles that a user or an app client can take on.
 */
export type ApiRole = "owner" | "administrator" | "billing_administrator" | "corpus_administrator";
export const ApiRole = {
    Owner: "owner",
    Administrator: "administrator",
    BillingAdministrator: "billing_administrator",
    CorpusAdministrator: "corpus_administrator",
} as const;
