/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AuthResponse {
    /** The bearer token you will pass in to subsequent API calls to authenticate. */
    accessToken: string;
    /** Tells you how long (in seconds) until your bearer token expires. */
    expiresIn: number;
    /** Will always be "Bearer" */
    tokenType: string;
}
