/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

export interface ChainReranker {
    type: "chain";
    /** Specify an array of rerankers to apply to search results consecutively. */
    rerankers: Vectara.SearchReranker[];
}
