/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information about the chat.
 */
export interface ChatInfoResponse {
    type: "chat_info";
    /** ID of the chat. */
    chatId?: string;
    /** ID of the turn. */
    turnId?: string;
}
