/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A message in the chat completion request, representing part of the conversation.
 */
export interface ChatCompletionRequestMessage {
    /** The role of the author of this message. Common values include 'system', 'user', 'assistant', 'function', and 'tool'. */
    role: string;
    /** The contents of the message. */
    content: string;
    /** The name of the author of this message, used to connect messages in a conversation. */
    name?: string;
}
