/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * Choose how to split documents into chunks during indexing. This is optional - if you do not set a chunking strategy, the platform uses the default strategy which creates one chunk (docpart) per sentence.
 */
export type ChunkingStrategy = Vectara.MaxCharsChunkingStrategy | Vectara.SentenceChunkingStrategy;
