/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

export type ComponentsSchemasCreateOpenAiEncoderRequest = Vectara.CreateOpenAiEncoderRequest;
