/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CorpusLimits {
    /** The number of bytes contained in the corpus. */
    usedBytes?: number;
    /** The maximum number of bytes the corpus can be. */
    maxBytes?: number;
    /** The maximum size that metadata can be on documents. */
    maxMetadataBytes?: number;
    /** The maximum per-second addition of new documents to corpus. */
    indexRate?: number;
}
