/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

/**
 * Create an App Client which allows you to call Vectara APIs using OAuth 2.0 client credentials.
 */
export interface CreateClientCredentialsRequest {
    /** Name of the client credentials. */
    name: string;
    /** Description of the client credentials. */
    description?: string;
    type: "client_credentials";
    /** API roles that the client credentials will have. */
    apiRoles?: Vectara.ApiRole[];
}
