/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * The response object for streaming chat completions in chunks.
 */
export interface CreateChatCompletionStreamResponse {
    /** The object type, which is always 'chat.completion.chunk' for streaming responses. */
    object: "chat.completion.chunk";
    /** A list of chat completion chunks. */
    choices: Vectara.ChatCompletionStreamResponseChoice[];
    /** Accepts any additional properties */
    [key: string]: any;
}
