/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * Response object containing the generated chat completion.
 */
export interface CreateChatCompletionResponse {
    /** The object type, which is always 'chat.completion'. */
    object: "chat.completion";
    /** A list of chat completion choices. Can be more than one if `n` is greater than `1`. */
    choices: Vectara.ChatCompletionResponseChoice[];
    /** Accepts any additional properties */
    [key: string]: any;
}
