/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A general error response with an error code and message.
 */
export interface Error_ {
    /** The messages describing why the error occurred. */
    messages?: string[];
    /** The ID of the request that can be used to help Vectara support debug what went wrong. */
    request_id?: string;
}
