/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Results of the factual consistency evaluation.
 */
export interface EvaluateFactualConsistencyResponse {
    /** A prediction score (0.0-1.0) from HHEM, monotonically indicates the likelihood of hallucinations. */
    score: number;
}
