/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

export interface FilterAttribute {
    /** The JSON path of the filter attribute in a document or document part metadata. */
    name: string;
    /** Indicates whether this is a document or document part metadata filter. */
    level: Vectara.FilterAttributeLevel;
    /** Description of the filter. May be omitted. */
    description?: string;
    /** Indicates whether an index should be created for the filter. Creating an index will improve query latency when using the filter. */
    indexed?: boolean;
    /** The value type of the filter. */
    type: Vectara.FilterAttributeType;
}
