/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Event containing information on how the generation was accomplished.
 */
export interface GenerationInfo {
    type: "generation_info";
    /**
     * The rendered prompt sent to the LLM. Useful when creating customer `prompt_text` templates. Only available
     * to Scale customers.
     */
    renderedPrompt?: string;
    /**
     * If you are on the Scale plan, you can view the actual query made to backend that was rephrased
     * by the LLM from the input query.
     */
    rephrasedQuery?: string;
}
