/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The generation by an LLM.
 */
export interface GenerationSpan {
    type: "generation";
    /** Time taken in milliseconds. */
    latency_millis?: number;
    /** When the span started. */
    started_at?: string;
    /** The text sent as a prompt to the LLM. */
    prompt?: string;
    /** The text generated from the LLM. */
    generation?: string;
}
