/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * The response that contains the hallucination correction results.
 */
export interface HallucinationCorrectionResponse {
    /** A list of corrections applied to the text, with explanations. */
    corrections: Vectara.CorrectionItem[];
    /** The revised version of the text, with minimal edits made to correct unsupported or inaccurate statements. If no corrections are needed, this value is identical to the original text. */
    corrected_text: string;
    /** The name of the model used for hallucination correction. */
    model?: string;
}
