/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

/**
 * An individual ranked search result from a query.
 */
export interface IndividualSearchResult {
    /** The document part altered by the context configuration that matches the query. */
    text?: string;
    /** The score of the individual result. */
    score?: number;
    /** The metadata for the document part. */
    partMetadata?: Record<string, unknown>;
    /** The metadata for the document that contains the document part. */
    documentMetadata?: Record<string, unknown>;
    /** The ID of the document that contains the document part. */
    documentId?: string;
    /** The table that the document part is from. */
    table?: Vectara.Table;
    /**
     * A query request can search over multiple corpora at a time. This property
     * is set to the index in the list of corpora in the original search request that this
     * search result originated from.
     *
     * If the query request is only over one corpus, this property is 0.
     */
    requestCorporaIndex?: number;
}
