/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * Response containing a list of Large Language Models available for generative AI capabilities.
 */
export interface ListLlMsResponse {
    /** List of LLMs. */
    llms?: Vectara.Llm[];
    metadata?: Vectara.ListMetadata;
}
