/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

export interface ListChatsResponse {
    /** List of chats. */
    chats?: Vectara.Chat[];
    metadata?: Vectara.ListMetadata;
}
