/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

export interface ListLlMsResponse {
    /** List of LLMs. */
    llms?: Vectara.Llm[];
    metadata?: Vectara.ListMetadata;
}
