/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

export interface ListDocumentsResponse {
    /** List of documents. */
    documents?: Vectara.Document[];
    metadata?: Vectara.ListMetadata;
}
