/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * Response containing a list of chat conversations.
 */
export interface ListChatsResponse {
    /** List of chats. */
    chats?: Vectara.Chat[];
    metadata?: Vectara.ListMetadata;
}
