/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

export interface ListApiKeysResponse {
    /** List of API keys. */
    apiKeys?: Vectara.ApiKey[];
    metadata?: Vectara.ListMetadata;
}
