/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

export interface ListJobsResponse {
    /** An array of jobs. */
    jobs?: Vectara.Job[];
    metadata?: Vectara.ListMetadata;
}
