/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A prompt that can be used with a LLM. A prompt is the template that is used to render
 * the text sent to the LLM. It also contains various default model settings such as
 * temperature.
 */
export interface Prompt {
    /** The ID of the prompt. */
    id?: string;
    /** Name of the prompt. This is used as the `prompt_name` in a query. */
    name?: string;
    /** The description of the prompt. */
    description?: string;
    /** Indicates whether the prompt is enabled. */
    enabled?: boolean;
    /** Indicates if this prompt is the default prompt used with the LLM. */
    default?: boolean;
}
