/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * A complete record of a previously executed query, including the request parameters and response.
 */
export interface QueryHistory {
    /** The ID of the query history. */
    id?: string;
    query?: unknown;
    /** The ID of the chat the query is a part of. */
    chat_id?: string;
    /** Time taken to complete the query, measured in milliseconds. */
    latency_millis?: number;
    /** ISO date time indicating when the query was first received. */
    started_at?: string;
    /** Parts of the query pipeline. Each span explains what happened during that stage of the query pipeline. */
    spans?: Vectara.QueryHistorySpan[];
}
