/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Non-fatal warnings that occurred during query processing.
 *  *  `exceeded_max_input_length_fcs`: The input to the Factual Consistency Score model exceeded the maximum allowed length, so no score is being returned
 */
export type QueryWarning = "exceeded_max_input_length_fcs";
