/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * Portion of the query history.
 */
export type QueryHistorySpan =
    | Vectara.RephraseSpan
    | Vectara.SearchSpan
    | Vectara.RerankSpan
    | Vectara.GenerationSpan
    | Vectara.FactualConsistencyScoreSpan
    | Vectara.RewrittenQuerySpan;
