/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface QueryHistorySummary {
    /** The ID of the query history. */
    id?: string;
    /** The actual query made. */
    query?: string;
    /** The corpus key that the query was made on. */
    corpusKey?: string;
    /** ISO date time indicating when the query was first received. */
    startedAt?: Date;
    /** Time that the query took in milliseconds. */
    latencyMillis?: number;
    /** The unique ID of the chat associated with the query, if this query is part of a chat. */
    chatId?: string;
    /** Generated response to the query, if requested. */
    generation?: string;
    /** The factual consistency score of the generation. */
    factualConsistencyScore?: number;
}
