/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

/**
 * The full response to a RAG query when the result is not streamed.
 */
export interface QueryFullResponse {
    /** The summary of the search results. */
    summary?: string;
    responseLanguage?: Vectara.Language;
    /** The ranked search results. */
    searchResults?: Vectara.IndividualSearchResult[];
    /**
     * Indicates the probability that the summary is factually consistent with the results.
     * The system excludes this property if it encounters excessively large outputs or search
     * results.
     */
    factualConsistencyScore?: number;
    /** The rendered prompt sent to the LLM. Useful when creating customer `prompt_template` templates. */
    renderedPrompt?: string;
    /** Non-fatal warnings that occurred during request processing */
    warnings?: Vectara.QueryWarning[];
}
