/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A summary of a previously executed query, including metadata but not full results.
 */
export interface QueryHistorySummary {
    /** The ID of the query history. */
    id?: string;
    /** The actual query made. */
    query?: string;
    /** The corpus key that the query was made on. */
    corpus_key?: string;
    /** ISO date time indicating when the query was first received. */
    started_at?: string;
    /** Time that the query took in milliseconds. */
    latency_millis?: number;
    /** The unique ID of the chat associated with the query, if this query is part of a chat. */
    chat_id?: string;
    /** Generated response to the query, if requested. */
    generation?: string;
    /** The factual consistency score of the generation. */
    factual_consistency_score?: number;
}
