/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

/**
 * An individual event sent with SSE when the query request is streamed.
 */
export type QueryStreamedResponse =
    | Vectara.StreamSearchResponse
    | Vectara.StreamGenerationChunk
    | Vectara.StreamGenerationEnd
    | Vectara.FactualConsistencyScore
    | Vectara.GenerationInfo
    | Vectara.StreamError
    | Vectara.StreamResponseEnd;
