/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * Authentication configuration for an LLM
 */
export type RemoteAuth = Vectara.BearerAuth | Vectara.HeaderAuth;
