/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * During the query pipeline, the query may be rephrased to better suit the corpus.
 */
export interface RephraseSpan {
    type: "rephrase";
    /** Time taken in milliseconds. */
    latencyMillis?: number;
    /** When the span started. */
    startedAt?: Date;
    /** Query made to the corpora. */
    rephrasedQuery?: string;
}
