/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

/**
 * The reranking of the search result.
 */
export interface RerankSpan {
    type: "rerank";
    /** Time taken in milliseconds. */
    latencyMillis?: number;
    /** When the span started. */
    startedAt?: Date;
    /** The new search results after reranking. */
    rerankedSearchResults?: Vectara.RerankedSearchResult[];
}
