/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

/**
 * The search portion of the query pipeline. This occurs before any reranking span.
 */
export interface SearchSpan {
    type: "search";
    /** Time taken in milliseconds. */
    latencyMillis?: number;
    /** Indicates when the span started. */
    startedAt?: Date;
    /** The search results before reranking. */
    searchResults?: Vectara.IndividualSearchResult[];
}
