/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * The search portion of the query pipeline. This occurs before any reranking span.
 */
export interface SearchSpan {
    type: "search";
    /** Time taken in milliseconds. */
    latency_millis?: number;
    /** ISO date time that indicates when the span started. */
    started_at?: string;
    /** The search results before reranking. */
    search_results?: Vectara.IndividualSearchResult[];
}
