/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * Search parameters to retrieve knowledge for the query.
 */
export interface SearchParameters {
    /** Specifies how many results into the result to skip. This is useful for pagination. */
    offset?: number;
    /** The maximum number of results returned. */
    limit?: number;
    context_configuration?: Vectara.ContextConfiguration;
    reranker?: Vectara.SearchReranker;
}
