/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Sets a chunking strategy that creates one chunk per sentence. This is the default strategy used when no chunking strategy is specified.
 */
export interface SentenceChunkingStrategy {
    type: "sentence_chunking_strategy";
}
