/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

/**
 * A logical section within a structured document.
 */
export interface StructuredDocumentSection {
    /** The section ID. Gets converted to a metadata field. */
    id?: number;
    /** The section title. */
    title?: string;
    /** The text of the section. */
    text: string;
    /**
     * Arbitrary object that becomes document part level metadata on any document part created
     * by this section. Properties of this object can be used by document part level
     * filters if defined as a corpus filter attribute.
     */
    metadata?: Record<string, unknown>;
    /** The sections that this section contains. */
    sections?: Vectara.StructuredDocumentSection[];
}
