/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index";

/**
 * A document with layout features.
 */
export interface StructuredDocument {
    /** The Document ID, must be unique within the corpus. */
    id: string;
    type: "structured";
    /** The title of the document. */
    title?: string;
    /** The description of the document. */
    description?: string;
    /**
     * The metadata for a document and is an arbitrary JSON object. Properties of this object
     * can be used by document level filter attributes.
     */
    metadata?: Record<string, unknown>;
    customDimensions?: Vectara.CustomDimensions;
    /** The subsection of the document. */
    sections: Vectara.StructuredDocumentSection[];
}
