/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * An individual event sent with Server-sent Events (SSE) when the document summarization request is streamed.
 */
export type SummarizeDocumentStreamedResponse =
    | Vectara.StreamGenerationChunk
    | Vectara.GenerationInfo
    | Vectara.StreamGenerationEnd
    | Vectara.StreamError
    | Vectara.StreamResponseEnd;
