/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * (Optional) Configuration for table extraction from the document.
 */
export interface TableExtractionConfig {
    /**
     * If set to true, the platform will attempt to extract tables from the document.
     * The tables will be indexed as separate document parts.
     */
    extractTables: boolean;
}
