/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../index.js";

/**
 * A user account with associated profile information and permissions.
 */
export interface User {
    /** The Vectara ID for the user. */
    id?: string;
    /** The email address for the user. */
    email?: string;
    /** The username for the user. */
    username?: string;
    /** Indicates whether the user is enabled or disabled. */
    enabled?: boolean;
    /** The description of the user. */
    description?: string;
    /** When the user was created. */
    created_at?: string;
    /** When a user property was last updated. */
    updated_at?: string;
    /** The role names of the user. */
    api_roles?: Vectara.ApiRole[];
    api_policy?: Vectara.ApiPolicy;
}
