/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UserFunctionReranker {
    type: "userfn";
    /** The user defined function. */
    userFunction?: string;
}
