/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../index";

/**
 * @example
 *     {
 *         query: "Am I allowed to bring pets to work?",
 *         search: {}
 *     }
 */
export interface QueryRequest {
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    requestTimeout?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    requestTimeoutMillis?: number;
    /** The search query string, which is the question the user is asking. */
    query: string;
    search: Vectara.SearchCorporaParameters;
    generation?: Vectara.GenerationParameters;
}
