/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         query: "query"
 *     }
 *
 * @example
 *     {
 *         query: "query"
 *     }
 *
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface CorporaSearchRequest {
    /**
     * The search query string for the corpus, which is the question the user is asking.
     */
    query: string;
    /**
     * The maximum number of top retrieval results to rerank and return.
     */
    limit?: number;
    /**
     * The position from which to start in the result set.
     */
    offset?: number;
    /**
     * Indicates whether to save the query in the query history.
     */
    save_history?: boolean;
    /**
     * [Tech Preview] Indicates whether to enable intelligent query rewriting. When enabled, the platform will attempt to extract metadata filter and rewrite the query to improve search results. Read [here](https://docs.vectara.com/docs/search-and-retrieval/intelligent-query-rewriting) for more details.
     */
    intelligent_query_rewriting?: boolean;
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    "Request-Timeout"?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    "Request-Timeout-Millis"?: number;
}
