/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface CorporaListRequest {
    /**
     * The maximum number of corpora to return at one time.
     */
    limit?: number;
    /**
     * A regular expression to filter the corpora by their name or summary.
     */
    filter?: string;
    /**
     * Used to retrieve the next page of corpora after the limit has been reached.
     */
    pageKey?: string;
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    requestTimeout?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    requestTimeoutMillis?: number;
}
