/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../../index";

/**
 * @example
 *     {
 *         filterAttributes: [{
 *                 name: "Title",
 *                 level: Vectara.FilterAttributeLevel.Document,
 *                 type: Vectara.FilterAttributeType.Integer
 *             }]
 *     }
 */
export interface ReplaceFilterAttributesRequest {
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    requestTimeout?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    requestTimeoutMillis?: number;
    /** The new filter attributes. */
    filterAttributes: Vectara.FilterAttribute[];
}
