/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const AuthResponse: core.serialization.ObjectSchema<serializers.AuthResponse.Raw, Vectara.AuthResponse> =
    core.serialization.object({
        accessToken: core.serialization.property("access_token", core.serialization.string()),
        expiresIn: core.serialization.property("expires_in", core.serialization.number()),
        tokenType: core.serialization.property("token_type", core.serialization.string()),
    });

export declare namespace AuthResponse {
    interface Raw {
        access_token: string;
        expires_in: number;
        token_type: string;
    }
}
