/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const Cell: core.serialization.ObjectSchema<serializers.Cell.Raw, Vectara.Cell> = core.serialization.object({
    textValue: core.serialization.property("text_value", core.serialization.string().optional()),
    intValue: core.serialization.property("int_value", core.serialization.number().optional()),
    floatValue: core.serialization.property("float_value", core.serialization.number().optional()),
    boolValue: core.serialization.property("bool_value", core.serialization.boolean().optional()),
    colspan: core.serialization.number().optional(),
    rowspan: core.serialization.number().optional(),
});

export declare namespace Cell {
    interface Raw {
        text_value?: string | null;
        int_value?: number | null;
        float_value?: number | null;
        bool_value?: boolean | null;
        colspan?: number | null;
        rowspan?: number | null;
    }
}
