/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const ChatInfoResponse: core.serialization.ObjectSchema<
    serializers.ChatInfoResponse.Raw,
    Vectara.ChatInfoResponse
> = core.serialization.object({
    type: core.serialization.stringLiteral("chat_info"),
    chatId: core.serialization.property("chat_id", core.serialization.string().optional()),
    turnId: core.serialization.property("turn_id", core.serialization.string().optional()),
});

export declare namespace ChatInfoResponse {
    interface Raw {
        type: "chat_info";
        chat_id?: string | null;
        turn_id?: string | null;
    }
}
