/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";
import { MaxCharsChunkingStrategy } from "./MaxCharsChunkingStrategy";

export const ComponentsSchemasMaxCharsChunkingStrategy: core.serialization.ObjectSchema<
    serializers.ComponentsSchemasMaxCharsChunkingStrategy.Raw,
    Vectara.ComponentsSchemasMaxCharsChunkingStrategy
> = MaxCharsChunkingStrategy;

export declare namespace ComponentsSchemasMaxCharsChunkingStrategy {
    type Raw = MaxCharsChunkingStrategy.Raw;
}
