/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const CustomerSpecificReranker: core.serialization.ObjectSchema<
    serializers.CustomerSpecificReranker.Raw,
    Vectara.CustomerSpecificReranker
> = core.serialization.object({
    type: core.serialization.stringLiteral("customer_reranker"),
    rerankerId: core.serialization.property("reranker_id", core.serialization.string().optional()),
    rerankerName: core.serialization.property("reranker_name", core.serialization.string().optional()),
    limit: core.serialization.number().optional(),
    cutoff: core.serialization.number().optional(),
});

export declare namespace CustomerSpecificReranker {
    interface Raw {
        type: "customer_reranker";
        reranker_id?: string | null;
        reranker_name?: string | null;
        limit?: number | null;
        cutoff?: number | null;
    }
}
