/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";
import { Header } from "./Header";
import { Row } from "./Row";
import { Cell } from "./Cell";

export const Data: core.serialization.ObjectSchema<serializers.Data.Raw, Vectara.Data> = core.serialization.object({
    headers: core.serialization.list(Header).optional(),
    rows: core.serialization.list(Row).optional(),
});

export declare namespace Data {
    interface Raw {
        headers?: Header.Raw[] | null;
        rows?: Row.Raw[] | null;
    }
}
