/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const ExtractionUsage: core.serialization.ObjectSchema<
    serializers.ExtractionUsage.Raw,
    Vectara.ExtractionUsage
> = core.serialization.object({
    tableExtractionUsed: core.serialization.property("table_extraction_used", core.serialization.number().optional()),
});

export declare namespace ExtractionUsage {
    interface Raw {
        table_extraction_used?: number | null;
    }
}
