/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const FilterAttributeLevel: core.serialization.Schema<
    serializers.FilterAttributeLevel.Raw,
    Vectara.FilterAttributeLevel
> = core.serialization.enum_(["document", "part"]);

export declare namespace FilterAttributeLevel {
    type Raw = "document" | "part";
}
