/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";
import { Cell } from "./Cell";

export const Header: core.serialization.Schema<serializers.Header.Raw, Vectara.Header> = core.serialization.list(Cell);

export declare namespace Header {
    type Raw = Cell.Raw[];
}
