/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const JobState: core.serialization.Schema<serializers.JobState.Raw, Vectara.JobState> = core.serialization.enum_(
    ["unknown", "queued", "started", "completed", "failed", "failed_will_retry", "aborted"]
);

export declare namespace JobState {
    type Raw = "unknown" | "queued" | "started" | "completed" | "failed" | "failed_will_retry" | "aborted";
}
