/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";
import { Job } from "./Job";
import { ListMetadata } from "./ListMetadata";

export const ListJobsResponse: core.serialization.ObjectSchema<
    serializers.ListJobsResponse.Raw,
    Vectara.ListJobsResponse
> = core.serialization.object({
    jobs: core.serialization.list(Job).optional(),
    metadata: ListMetadata.optional(),
});

export declare namespace ListJobsResponse {
    interface Raw {
        jobs?: Job.Raw[] | null;
        metadata?: ListMetadata.Raw | null;
    }
}
