/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";
import { AppClient } from "./AppClient";
import { ListMetadata } from "./ListMetadata";

export const ListAppClientsResponse: core.serialization.ObjectSchema<
    serializers.ListAppClientsResponse.Raw,
    Vectara.ListAppClientsResponse
> = core.serialization.object({
    appClients: core.serialization.property("app_clients", core.serialization.list(AppClient).optional()),
    metadata: ListMetadata.optional(),
});

export declare namespace ListAppClientsResponse {
    interface Raw {
        app_clients?: AppClient.Raw[] | null;
        metadata?: ListMetadata.Raw | null;
    }
}
