/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";
import { GenerationPreset } from "./GenerationPreset";
import { ListMetadata } from "./ListMetadata";

export const ListGenerationPresetsResponse: core.serialization.ObjectSchema<
    serializers.ListGenerationPresetsResponse.Raw,
    Vectara.ListGenerationPresetsResponse
> = core.serialization.object({
    generationPresets: core.serialization.property(
        "generation_presets",
        core.serialization.list(GenerationPreset).optional()
    ),
    metadata: ListMetadata.optional(),
});

export declare namespace ListGenerationPresetsResponse {
    interface Raw {
        generation_presets?: GenerationPreset.Raw[] | null;
        metadata?: ListMetadata.Raw | null;
    }
}
