/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";
import { Chat } from "./Chat";
import { ListMetadata } from "./ListMetadata";

export const ListChatsResponse: core.serialization.ObjectSchema<
    serializers.ListChatsResponse.Raw,
    Vectara.ListChatsResponse
> = core.serialization.object({
    chats: core.serialization.list(Chat).optional(),
    metadata: ListMetadata.optional(),
});

export declare namespace ListChatsResponse {
    interface Raw {
        chats?: Chat.Raw[] | null;
        metadata?: ListMetadata.Raw | null;
    }
}
