/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const MmrReranker: core.serialization.ObjectSchema<serializers.MmrReranker.Raw, Vectara.MmrReranker> =
    core.serialization.object({
        type: core.serialization.stringLiteral("mmr"),
        diversityBias: core.serialization.property("diversity_bias", core.serialization.number().optional()),
    });

export declare namespace MmrReranker {
    interface Raw {
        type: "mmr";
        diversity_bias?: number | null;
    }
}
