/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const NoneReranker: core.serialization.ObjectSchema<serializers.NoneReranker.Raw, Vectara.NoneReranker> =
    core.serialization.object({
        type: core.serialization.stringLiteral("none"),
    });

export declare namespace NoneReranker {
    interface Raw {
        type: "none";
    }
}
