/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const NotFoundErrorBody: core.serialization.ObjectSchema<
    serializers.NotFoundErrorBody.Raw,
    Vectara.NotFoundErrorBody
> = core.serialization.object({
    id: core.serialization.string().optional(),
    messages: core.serialization.list(core.serialization.string()).optional(),
    requestId: core.serialization.property("request_id", core.serialization.string().optional()),
});

export declare namespace NotFoundErrorBody {
    interface Raw {
        id?: string | null;
        messages?: string[] | null;
        request_id?: string | null;
    }
}
