/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const ReplaceFilterAttributesResponse: core.serialization.ObjectSchema<
    serializers.ReplaceFilterAttributesResponse.Raw,
    Vectara.ReplaceFilterAttributesResponse
> = core.serialization.object({
    jobId: core.serialization.property("job_id", core.serialization.string()),
});

export declare namespace ReplaceFilterAttributesResponse {
    interface Raw {
        job_id: string;
    }
}
