/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";
import { Cell } from "./Cell";

export const Row: core.serialization.Schema<serializers.Row.Raw, Vectara.Row> = core.serialization.list(Cell);

export declare namespace Row {
    type Raw = Cell.Raw[];
}
