/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vectara from "../../api/index";
import * as core from "../../core";

export const StreamResponseEnd: core.serialization.ObjectSchema<
    serializers.StreamResponseEnd.Raw,
    Vectara.StreamResponseEnd
> = core.serialization.object({
    type: core.serialization.stringLiteral("end"),
});

export declare namespace StreamResponseEnd {
    interface Raw {
        type: "end";
    }
}
