/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetQueryHistoriesRequest {
    /**
     * Specifies the `corpus_key` used in the query.
     */
    corpusKey?: string;
    /**
     * Queries that started after a particular date-time.
     */
    startedAfter?: Date;
    /**
     * Queries that started before a particular date-time.
     */
    startedBefore?: Date;
    /**
     * Specifies the chat_id of the query, this will return all queries in the specified chat.
     */
    chatId?: string;
    /**
     * Specifies the maximum number of query history listed.
     */
    limit?: number;
    /**
     * Used to retrieve the next page of query histories after the limit has been reached.
     */
    pageKey?: string;
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    requestTimeout?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    requestTimeoutMillis?: number;
}
