/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../../index";

/**
 * @example
 *     {
 *         query: "string",
 *         search: {
 *             corpora: [{}],
 *             offset: 1,
 *             limit: 1,
 *             contextConfiguration: {},
 *             reranker: {}
 *         },
 *         generation: {
 *             promptName: "string",
 *             maxUsedSearchResults: 1,
 *             promptText: "string",
 *             maxResponseCharacters: 1,
 *             responseLanguage: Vectara.Language.Auto,
 *             modelParameters: {
 *                 maxTokens: 1,
 *                 temperature: 1.1,
 *                 frequencyPenalty: 1.1,
 *                 presencePenalty: 1.1
 *             },
 *             citations: {},
 *             enableFactualConsistencyScore: true
 *         },
 *         chat: {
 *             store: true
 *         }
 *     }
 */
export interface ChatsCreateTurnStreamRequest {
    /** The chat message or question. */
    query: string;
    search: Vectara.SearchCorporaParameters;
    generation?: Vectara.GenerationParameters;
    chat?: Vectara.ChatParameters;
}
