/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "What are the carbon reduction efforts by EU banks in 2023?",
 *         search: {}
 *     }
 */
export interface ChatsCreateTurnsRequest {
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    "Request-Timeout"?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    "Request-Timeout-Millis"?: number;
    /** The chat message or question. */
    query: string;
    search: Vectara.SearchCorporaParameters;
    generation?: Vectara.GenerationParameters;
    chat?: Vectara.ChatParameters;
    /** Indicates whether to save the chat in both the chat and query history. This overrides `chat.store`. */
    save_history?: boolean;
    /** [Tech Preview] Indicates whether to enable intelligent query rewriting. When enabled, the platform will attempt to extract metadata filter and rewrite the query to improve search results. Read [here](https://docs.vectara.com/docs/search-and-retrieval/intelligent-query-rewriting) for more details. */
    intelligent_query_rewriting?: boolean;
}
