/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UpdateTurnRequest {
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    "Request-Timeout"?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    "Request-Timeout-Millis"?: number;
    /** Indicates whether to disable a turn. It will disable this turn and all subsequent turns. Enabling a turn is not implemented. */
    enabled?: boolean;
}
