/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../../index";

/**
 * @example
 *     {}
 */
export interface UpdateAppClientRequest {
    /** The new App Client description. */
    description?: string;
    /** The new roles attached to the App Client. These roles will replace the current roles. */
    apiRoles?: Vectara.ApiRole[];
}
