/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../../index";

/**
 * @example
 *     {
 *         email: "email"
 *     }
 */
export interface CreateUserRequest {
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    requestTimeout?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    requestTimeoutMillis?: number;
    /** The email address for the user. */
    email: string;
    /** The username for the user. The value defaults to the email. */
    username?: string;
    /** The description of the user. */
    description?: string;
    /** The role names assigned to the user. */
    apiRoles?: Vectara.ApiRole[];
}
