/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {}
 *     }
 */
export interface DocumentsUpdateRequest {
    /**
     * The API will make a best effort to complete the request in the specified seconds or time out.
     */
    "Request-Timeout"?: number;
    /**
     * The API will make a best effort to complete the request in the specified milliseconds or time out.
     */
    "Request-Timeout-Millis"?: number;
    body: Vectara.UpdateDocumentRequest;
}
