/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../../index";

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface QueriesQueryCorpusRequest {
    /** The query to receive an answer on. */
    query: string;
    /** The parameters to search one corpus. */
    search?: Vectara.SearchCorpusParameters;
    generation?: Vectara.GenerationParameters;
}
