/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vectara from "../../../../index";

/**
 * @example
 *     {
 *         query: "Am I allowed to bring pets to work?",
 *         search: {}
 *     }
 */
export interface QueriesQueryRequest {
    /** The query to receive an answer on. */
    query: string;
    search: Vectara.SearchCorporaParameters;
    generation?: Vectara.GenerationParameters;
}
